### ISSUE TITLE
Sha in library?

### ISSUE THREAD

**Issue by nroose** [RedpointGames/gcloud-pipeline-library#1]
I keep getting a git error with the sha fea5cb455b3f835cae50d9fe1447be2007e8d574 in the command. Perhaps it's hardcoded?

**Comment by hach-que** [comment]
(Based on the comment left on the commit) This sounds like a Jenkins configuration problem or build agent problem, rather than an issue with this plugin, so I'm going to close this issue. That commit works fine on multiple Jenkins instances I have.
