### ISSUE TITLE
Extra n in latest commit

### ISSUE THREAD

**Issue by JC1738** [RedpointGames/gcloud-pipeline-library#2]
+ echo -e /home/jenkins/agent/workspace/Rails_prebuild-test-credentials/.gcloud/serviceaccount.json
n
+ gsutil config -e -o /home/jenkins/agent/workspace/Rails_prebuild-test-credentials/.gcloud/boto.cfg
+ echo -e /home/jenkins/agent/workspace/Rails_prebuild-test-credentials/.gcloud/serviceaccount.json
n

Related to       sh 'echo -e "$GOOGLE_APPLICATION_CREDENTIALS\nn" | gsutil config -e -o "$CLOUDSDK_CONFIG/boto.cfg"'

https://github.com/RedpointGames/gcloud-pipeline-library/blob/75a5be14cfab3caf522c2cc3bc697c434664d40d/vars/gcloud.groovy#L25

**Comment by JC1738** [comment]
I verified reverting this commit on our fork and pointing jenkins to the forked repo our builds now can find the credentials again.

**Comment by hach-que** [comment]
On newer versions of gcloud, gsutil requires an extra "n" to answer a prompt about permissions. Without answering the prompt, boto.cfg isn't generated. I'd expect that the extra "n" to be silently ignored on older versions.

What is the error output you're seeing in Jenkins?

**Comment by JC1738** [comment]
<img width="1142" alt="Screen Shot 2019-08-03 at 8 48 59 AM" src="https://user-images.githubusercontent.com/3421783/62418027-716bc480-b614-11e9-84a0-55f1c02d8d18.png">

@hach-que

**Comment by hach-que** [comment]
Oh, your version of echo doesn't support `-e`. Are you using bash or sh as the default shell?

**Comment by JC1738** [comment]
Well, isn't this error just in the stage provided by your library?  How do I tell the default shell for the Pipeline Jenkinsfile?  I don't think we set anything special in the options step.

**Comment by hach-que** [comment]
The library just uses the `sh` step to call into `gsutil`. The shell being used by Jenkins is probably going to depend on either what `/bin/sh` is symlink'd to, or the user's default shell for the user that the Jenkins agent is running as / SSHing into the node as.

Can you let me know if replacing the `sh 'echo -e ...'` line in your fork with the following works for you?

`sh 'printf "$GOOGLE_APPLICATION_CREDENTIALS\nn" | gsutil config -e -o "$CLOUDSDK_CONFIG/boto.cfg"'`

**Comment by JC1738** [comment]
@hach-que 
https://github.com/RepairPal/gcloud-pipeline-library/commit/2f7c31451cab269a72c07d6e211f871451aed8be

This worked
<img width="1014" alt="Screen Shot 2019-08-03 at 11 14 32 PM" src="https://user-images.githubusercontent.com/3421783/62420297-af80dc80-b644-11e9-8d5b-22e6b07bcf58.png">

Thank you for updating the ReadMe about the versioning as well as working through this issue with us.  We appreciate your library and it helps us leverage Jenkins and Google Cloud.

Thanks!
